# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
# RUN npm install primeicons --save

# Copy the Angular app source code
COPY . .

# Expose the port Angular CLI uses
EXPOSE 4200

# Run the Angular app
CMD ["npm", "start", "--", "--host", "localhost"]