version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
    depends_on:
      - json-server
    networks:
      - library-network
    # For better development experience, uncomment:
    # volumes:
      # - /dist/library-system:/usr/share/nginx/html

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
      # - ./cors-middleware.js:/app/cors-middleware.js
    networks:
      - library-network
    # For healthcheck option:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/books"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  library-network:
    driver: bridge