services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200" # Expose Angular app on port 4200
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Fix for file watching in Docker
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000" # Expose JSON server on port 3000
    volumes:
      - ./db.json:/app/db.json