name: Develop Branch Push Notification

on:
  push:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Show success message
        run: |
          echo "===================================="
          echo "✅ Successfully pushed to develop branch!"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Pushed by: ${{ github.actor }}"
          echo "Push timestamp: $(date)"
          echo "===================================="
      
      - name: List changed files
        run: |
          echo "Files changed in this commit:"
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} || echo "Could not determine changed files"
          
      - name: Repository summary
        run: |
          echo "Repository summary:"
          echo "- Total files: $(find . -type f | wc -l)"
          echo "- JavaScript files: $(find . -name "*.js" | wc -l)"
          echo "- TypeScript files: $(find . -name "*.ts" | wc -l)"
          echo "- HTML files: $(find . -name "*.html" | wc -l)"
          echo "- CSS files: $(find . -name "*.css" | wc -l)"