name: Build and Push Docker Images

on:
  push:
    branches: [ docker-servers ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build --if-present
      
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  docker:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push Angular image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.angular
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library-system:latest,${{ secrets.DOCKER_HUB_USERNAME }}/library-system:${{ github.sha }}
          
      - name: Build and push JSON Server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.json-server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/library-system-json-server:latest,${{ secrets.DOCKER_HUB_USERNAME }}/library-system-json-server:${{ github.sha }}